[project]
name = "ComfyUI"
version = "0.5.1"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9"

[project.urls]
homepage = "https://www.comfy.org/"
repository = "https://github.com/comfyanonymous/ComfyUI"
documentation = "https://docs.comfy.org/"

[tool.ruff]
lint.select = [
  "N805", # invalid-first-argument-name-for-method
  "S307", # suspicious-eval-usage
  "S102", # exec
  "T",    # print-usage
  "W",
  # The "F" series in Ruff stands for "Pyflakes" rules, which catch various Python syntax errors and undefined names.
  # See all rules here: https://docs.astral.sh/ruff/rules/#pyflakes-f
  "F",
]
exclude = ["*.ipynb", "**/generated/*.pyi"]

[tool.mypy]
python_version = "3.12"
disable_error_code = ["import-untyped","override"]
mypy_path = "./out"
# Limit default type-checking scope to json_gui only.
files = ["json_gui"]

# Don't type-check imported project modules outside the target scope.
# This keeps the report focused on json_gui, but it can reduce cross-module type safety.
follow_imports = "skip"
exclude = [
    '\.venv/.*',
    '.+\.pyi',
    '/opt/.*',
    '.*/site-packages/.*',
    'custom_nodes/_ComfyUI-Logic\.disabled/.*',
    'custom_nodes/_ComfyUI_essentials\.disabled/.*',
    'workspace_temp/.*',
    'src/tests/.*',
    'tests/execution/testing_nodes/testing-pack/.*',
]

[tool.pylint.master]
load-plugins = ["workspace_temp.custom_checkers"]
ignore-patterns = ["\\.venv/.*", ".+\\.pyi", "/opt/.*",".*/site-packages/.*", "workspace_temp/.*"]

[tool.pylint.messages_control]
enable = ["MissingReturnTypeChecker"]
disable = ["R0903", "I1101", "C0301", "W0718"]

[tool.pylint.format]
max-line-length = 200

[tool.pylint.design]
max-args = 10
max-positional-arguments = 10
max-attributes = 12

[tool.flake8]
max-line-length = 120
ignore = [
    "E303", # too many blank lines
]
exclude = [
    ".venv",
    "build",
    "dist",
    "__pycache__",
    "*.pyc",
    "*.egg-info",
    "**/pylint/**",
    "src/tests/**"
]